version: '3'
services:
  falcon:
    build: ./falcon
    ports:
     - "8000:8000"
    links:
     - kafka
     - cassandra
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.0
    ports:
     - "9092:9092"
    hostname: kafka
    links: 
     - zookeeper
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=129.114.108.142
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_PORT=9092
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on: 
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - "50075:50075"
  spark-master:
    image: jupyter/pyspark-notebook
    container_name: spark-master
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    environment:
      - MASTER= spark://spark-master:7077
      - SPARK_CONF_DIR= /conf
      - SPARK_PUBLIC_DNS= localhost
    ports:
      - 4040
      - 6066
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - "7077:7077"
      - "8080:8080"
    env_file:
      - ./hadoop.env
    volumes:
     - ./conf/master:/conf
     - ./spark:/home/jovyan/work
     - ./mydata:/home/jovyan/work/data
    links:
     - kafka
     - cassandra
  spark-worker:
    image: jupyter/pyspark-notebook
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    links:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_CONF_DIR= /conf
      - SPARK_WORKER_CORES= 2
      - SPARK_WORKER_MEMORY= 2g
      - SPARK_WORKER_PORT= 8881
      - SPARK_WORKER_WEBUI_PORT= 8081
    ports:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - "8081:8081"
    env_file:
      - ./hadoop.env
    volumes:
      - ./conf/worker:/conf
      - ./spark:/home/jovyan/work
      - ./mydata:/home/jovyan/work/data

  notebook:
    image: jupyter/all-spark-notebook
    hostname: jupyter
    depends_on:
      - spark-master
      - cassandra
      - kafka
    links:
      - spark-master
      - kafka
      - cassandra
    environment:
      SPARK_OPTS: '--master=spark://spark-master:7077'
    ports:
      - "8888:8888"
    volumes:
      - ./spark:/home/jovyan/work
      - ./mydata:/home/jovyan/work/data
    command: "start-notebook.sh --NotebookApp.token=''"


  hue:
    image: bde2020/hdfs-filebrowser:3.11
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
  cassandra:
    image: "cassandra:3"
    volumes:
     - ./cassandra:/bdr
     - ./mydata:/data
    ports:
     - "7000:7000"
     - "7001:7001" 
     - "7199:7199"
     - "9042:9042"
     - "9160:9160"

